<?php
    require_once("class_database.php");
    require_once("class_artigos.php");
    require_once("class_login.php");
    require_once("emails.php");
    require_once("class_users.php");
    require_once("class_pesquisar.php");
    require_once("class_mensagens.php");
    require_once("class_notificacoes.php");
    require_once("class_consultas.php");
    require_once("class_treinos.php");
    require_once("class_dor.php");
    require_once("class_videos.php");
?>